Replace X-StorageApi-Token with X-KBC-ManageApiToken header
keboola/encryption-api-php-client pull request #7
Opened 2024-05-06 14:54 UTC by romantmb

`X-KBC-ManageApiToken` [is required](https://github.com/keboola/encryption-api/blob/92fcddeef1361bc05945477e893cb903fe16c9bb/tests/Controller/MigrateConfiguration/MigrateConfigurationActionTest.php#L29) at `POST /migrate-configuration` in service `encryption-api`

https://keboola.atlassian.net/browse/PST-1686

2024-05-06 14:56 UTC, romantmb commented
@odinuv Tohle mi uniklo a zjistil jsem to [až při testovací migraci](https://app.datadoghq.eu/logs?query=service%3Ajob-queue-runner%20%40component%3Akeboola.app-project-migrate%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY9OUVeVn906xQAAAAAAAAAYAAAAAEFZOU9VVjdVQUFCcV9jYTJMY3Fma3dBRwAAACQAAAAAMDE4ZjRlNTEtNjA5Ni00NGY1LTgxZmYtZTZmY2FmMjVjMTYy&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1715005028843&to_ts=1715005928843&live=true).

2024-05-07 08:07 UTC, odinuv requested changes
Ok řekli jsme, že nebudem tady dělat funkcionalní testy, to je ok. Ale, že se změní něco v kódu a ne v testech je 🔴, chybí tady teda test na to, co vlastně klient posílá - inspirace https://github.com/keboola/oauth-v2-php-client/blob/4b9f05db742c72d837a7c02fbefc76d541782b58/tests/CredentialsTest.php#L238

2024-05-07 08:36 UTC, romantmb commented
> Ok řekli jsme, že nebudem tady dělat funkcionalní testy, to je ok. Ale, že se změní něco v kódu a ne v testech je 🔴, chybí tady teda test na to, co vlastně klient posílá - inspirace https://github.com/keboola/oauth-v2-php-client/blob/4b9f05db742c72d837a7c02fbefc76d541782b58/tests/CredentialsTest.php#L238

@odinuv Díky za super hint. 🙂 Přidáno do testu.

2024-05-07 09:04 UTC, odinuv approved these changes
👍

2024-05-07 09:25 UTC, merged